# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://xindi-dumbledore.github.io
email: xindi.w1993@gmail.com
title: Xindi Wang (王 心迪)
author: Xindi Wang
description: Personal Website for Xindi Wang, Ph.D. 
copyright: 'Copyright &copy; 2012 Xindi Wang. All Rights Reserved.'
credits: 'Last Update: November, 2012'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/wangxindi/
  - title: github
    url: https://github.com/xindi-dumbledore
  - title: twitter
    url: https://twitter.com/albus931003
  - title: instagram
    url: https://www.instagram.com/albus_dumbledore_1993/