# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Xindi's Homepage
email: xindi.w1993@gmail.com
author: Xindi Wang
description: > # "Write an awesome description for your new site here. 
  Personal Website for Xindi Wang, Network Science PhD 
copyright: 'Copyright &copy; 2018 Xindi Wang. All Rights Reserved.'
credits: 'Last Update: April, 2018'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/xindi-dumbledore
  - title: linkedin
    url: https://www.linkedin.com/in/wangxindi/
  - title: twitter
    url: https://twitter.com/albus931003
